"use client";

import {
  CheckCircle2,
  Copy,
  ExternalLink,
  ArrowLeft,
  Download,
  FileText,
  Shield,
} from "lucide-react";
import { useState, useCallback } from "react";
import type { TransactionReceipt } from "@/hooks/use-pi-sdk";
import { cn } from "@/lib/utils";

interface TransactionSuccessProps {
  receipt: TransactionReceipt;
  vtuDelivery?: {
    delivery_id: string;
    mock_token_delivery_id: string;
    test_naira_balance: string;
  };
  onDone: () => void;
}

export function TransactionSuccess({
  receipt,
  vtuDelivery,
  onDone,
}: TransactionSuccessProps) {
  const [copied, setCopied] = useState<string | null>(null);
  const [isDownloading, setIsDownloading] = useState(false);

  const copyToClipboard = async (text: string, field: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(field);
      setTimeout(() => setCopied(null), 2000);
    } catch {
      console.error("Failed to copy");
    }
  };

  const formatTxId = (txid: string) => {
    if (txid.length <= 16) return txid;
    return `${txid.slice(0, 8)}...${txid.slice(-8)}`;
  };

  // Generate downloadable receipt (PDF-style text)
  const generateReceipt = useCallback(() => {
    const receiptContent = `
================================================================================
                           DATA HUB - TRANSACTION RECEIPT
                             Pi Network VTU Service
================================================================================

Transaction ID:     ${receipt.paymentId}
Date & Time:        ${receipt.timestamp.toLocaleString()}
Status:             SUCCESSFUL

--------------------------------------------------------------------------------
                              PAYMENT DETAILS
--------------------------------------------------------------------------------

Amount Paid:        ${receipt.amount.toFixed(4)} Pi
Network:            ${receipt.network_provider.toUpperCase()}
Phone Number:       ${receipt.phone_number}
Data Plan:          ${receipt.data_plan_size}

--------------------------------------------------------------------------------
                            BLOCKCHAIN DETAILS
--------------------------------------------------------------------------------

Pi Transaction Hash (TXID):
${receipt.txid}

Block Explorer:
https://piblockexplorer.com/tx/${receipt.txid}

${
  vtuDelivery
    ? `--------------------------------------------------------------------------------
                             VTU DELIVERY DETAILS
--------------------------------------------------------------------------------

Delivery ID:        ${vtuDelivery.delivery_id}
Token Delivery ID:  ${vtuDelivery.mock_token_delivery_id}
Naira Balance:      NGN ${vtuDelivery.test_naira_balance}
`
    : ""
}
--------------------------------------------------------------------------------
                           PiRC COMPLIANCE METADATA
--------------------------------------------------------------------------------

Service Type:       data_bundle
Provider Code:      ${receipt.network_provider.toUpperCase()}
Recipient:          ${receipt.phone_number}
Fulfillment:        COMPLETED

================================================================================
     Verified by Pi Network KYC - No additional registration required
     
     This receipt was generated by Data Hub VTU Service
     Powered by Pi Network (Testnet Environment)
================================================================================
    `.trim();

    return receiptContent;
  }, [receipt, vtuDelivery]);

  const downloadReceipt = useCallback(async () => {
    setIsDownloading(true);

    try {
      const content = generateReceipt();
      const blob = new Blob([content], { type: "text/plain" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `DataHub_Receipt_${receipt.paymentId.slice(0, 8)}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error("Failed to download receipt:", error);
    } finally {
      setIsDownloading(false);
    }
  }, [generateReceipt, receipt.paymentId]);

  return (
    <div className="flex min-h-screen flex-col bg-background">
      {/* Success Animation Header */}
      <div className="relative flex flex-col items-center justify-center px-6 pt-16 pb-8">
        {/* Animated circles */}
        <div className="absolute inset-0 flex items-center justify-center overflow-hidden">
          <div
            className="absolute h-64 w-64 animate-ping rounded-full bg-success/10"
            style={{ animationDuration: "2s" }}
          />
          <div
            className="absolute h-48 w-48 animate-ping rounded-full bg-success/15"
            style={{ animationDuration: "1.5s", animationDelay: "0.5s" }}
          />
        </div>

        {/* Success Icon */}
        <div className="relative mb-6 flex h-24 w-24 items-center justify-center rounded-full bg-success/20">
          <div className="flex h-16 w-16 items-center justify-center rounded-full bg-success">
            <CheckCircle2 className="h-10 w-10 text-success-foreground" />
          </div>
        </div>

        <h1 className="mb-2 text-2xl font-bold text-foreground">
          Data Successfully Sent!
        </h1>
        <p className="text-center text-muted-foreground">
          Your {receipt.data_plan_size} data bundle has been activated
        </p>
      </div>

      {/* Receipt Card */}
      <div className="flex-1 px-4 pb-8">
        <div className="rounded-2xl bg-card p-5 shadow-xl">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
              Transaction Receipt
            </h2>
            <div className="flex items-center gap-2">
              <FileText className="h-4 w-4 text-primary" />
            </div>
          </div>

          <div className="space-y-4">
            {/* Phone Number */}
            <div className="flex items-center justify-between">
              <span className="text-sm text-muted-foreground">Phone Number</span>
              <span className="font-mono font-medium text-foreground">
                {receipt.phone_number}
              </span>
            </div>

            {/* Network */}
            <div className="flex items-center justify-between">
              <span className="text-sm text-muted-foreground">Network</span>
              <span className="font-medium text-foreground uppercase">
                {receipt.network_provider}
              </span>
            </div>

            {/* Data Plan */}
            <div className="flex items-center justify-between">
              <span className="text-sm text-muted-foreground">Data Plan</span>
              <span className="font-medium text-foreground">
                {receipt.data_plan_size}
              </span>
            </div>

            {/* Amount */}
            <div className="flex items-center justify-between">
              <span className="text-sm text-muted-foreground">Amount Paid</span>
              <span className="font-semibold text-primary">
                {receipt.amount.toFixed(2)} Pi
              </span>
            </div>

            <div className="my-4 border-t border-border" />

            {/* Payment ID */}
            <div>
              <div className="mb-1 flex items-center justify-between">
                <span className="text-sm text-muted-foreground">Payment ID</span>
                <button
                  onClick={() => copyToClipboard(receipt.paymentId, "paymentId")}
                  className="flex items-center gap-1 text-xs text-primary hover:text-primary/80"
                >
                  <Copy className="h-3 w-3" />
                  {copied === "paymentId" ? "Copied!" : "Copy"}
                </button>
              </div>
              <p className="font-mono text-xs text-foreground break-all">
                {formatTxId(receipt.paymentId)}
              </p>
            </div>

            {/* Transaction ID */}
            <div>
              <div className="mb-1 flex items-center justify-between">
                <span className="text-sm text-muted-foreground">
                  Pi Transaction Hash (TXID)
                </span>
                <button
                  onClick={() => copyToClipboard(receipt.txid, "txid")}
                  className="flex items-center gap-1 text-xs text-primary hover:text-primary/80"
                >
                  <Copy className="h-3 w-3" />
                  {copied === "txid" ? "Copied!" : "Copy"}
                </button>
              </div>
              <p className="font-mono text-xs text-foreground break-all">
                {formatTxId(receipt.txid)}
              </p>
            </div>

            {/* VTU Delivery Details */}
            {vtuDelivery && (
              <>
                <div className="my-4 border-t border-border" />

                <div>
                  <div className="mb-1 flex items-center justify-between">
                    <span className="text-sm text-muted-foreground">
                      Mock Token Delivery ID
                    </span>
                    <button
                      onClick={() =>
                        copyToClipboard(
                          vtuDelivery.mock_token_delivery_id,
                          "deliveryId"
                        )
                      }
                      className="flex items-center gap-1 text-xs text-primary hover:text-primary/80"
                    >
                      <Copy className="h-3 w-3" />
                      {copied === "deliveryId" ? "Copied!" : "Copy"}
                    </button>
                  </div>
                  <p className="font-mono text-xs text-foreground">
                    {vtuDelivery.mock_token_delivery_id}
                  </p>
                </div>

                <div className="flex items-center justify-between">
                  <span className="text-sm text-muted-foreground">
                    Test Naira Balance
                  </span>
                  <span className="font-medium text-[#F59E0B]">
                    NGN {vtuDelivery.test_naira_balance}
                  </span>
                </div>
              </>
            )}

            {/* Timestamp */}
            <div className="flex items-center justify-between">
              <span className="text-sm text-muted-foreground">Date & Time</span>
              <span className="text-sm text-foreground">
                {receipt.timestamp.toLocaleString()}
              </span>
            </div>
          </div>

          {/* PiRC Compliance Badge */}
          <div className="mt-4 flex items-center justify-center gap-2 rounded-lg bg-success/10 px-3 py-2">
            <Shield className="h-4 w-4 text-success" />
            <span className="text-xs text-success">
              PiRC Service Payment Compliant
            </span>
          </div>

          {/* Action Buttons */}
          <div className="mt-6 grid grid-cols-2 gap-3">
            {/* Download Receipt */}
            <button
              onClick={downloadReceipt}
              disabled={isDownloading}
              className={cn(
                "flex items-center justify-center gap-2 rounded-xl bg-secondary py-3 text-sm font-medium text-foreground transition-colors hover:bg-secondary/80",
                isDownloading && "opacity-50 cursor-not-allowed"
              )}
            >
              <Download className="h-4 w-4" />
              {isDownloading ? "Saving..." : "Download"}
            </button>

            {/* View on Explorer */}
            <a
              href={`https://piblockexplorer.com/tx/${receipt.txid}`}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center justify-center gap-2 rounded-xl bg-secondary py-3 text-sm font-medium text-foreground transition-colors hover:bg-secondary/80"
            >
              <ExternalLink className="h-4 w-4" />
              Explorer
            </a>
          </div>
        </div>

        {/* Done Button */}
        <button
          onClick={onDone}
          className={cn(
            "mt-6 w-full rounded-2xl py-5 font-semibold transition-all duration-300",
            "bg-gradient-to-r from-primary via-accent to-primary bg-[length:200%_100%]",
            "text-primary-foreground shadow-xl shadow-primary/30",
            "hover:bg-[position:100%_0] hover:shadow-2xl hover:shadow-primary/40",
            "active:scale-[0.98]"
          )}
        >
          <div className="flex items-center justify-center gap-2">
            <ArrowLeft className="h-5 w-5" />
            <span className="text-lg">Back to Dashboard</span>
          </div>
        </button>
      </div>
    </div>
  );
}
